### PR TITLE
Docs: fix a typo under workflow essentials/restoring configurations.

### PR DESCRIPTION
**Pull request by jtagcat**

### CODE REVIEW

**Comment by avkonst** [comment]
Thanks

**Comment by jtagcat** [comment]
Thanks for putting in the time to write this whole thing, including quite professional documentation. I'd question how the heck there are only 3 stars on the repo.

**Comment by avkonst** [comment]
I have advertised it yesterday only :) please help the project to grow by
spreading few words about it in social media and blogs. Thanks

**Comment by jtagcat** [comment]
Where did you advertise?

I heard it from my hackerspace:
image

**Comment by avkonst** [comment]
I posted in few comments for blog posts. I do not know how to promote the
content online. If you can help / advise how to promote it would be great.

**Pull request merged**
